### ISSUE TITLE
It doesn't work on 32 bits os'es

### ISSUE THREAD

**Issue by mr-f0xx** [equeim/xfce4-alsa-plugin#6]
Can you please make it compatible for 32 bits os'es like twisterOS for raspberry pi? It doesn't work sadly

**Comment by equeim** [comment]
Could you be more specific, how exactly it doesn't work?

**Comment by mr-f0xx** [comment]
Sorry for the little information in my first post but apparently there is a problem with the dependencies.

This is the issue ::

meson.build:12:0: ERROR: Invalid version of dependency, need 'libxfce4panel-2.0' ['>= 4.13.0'] found '4.12.2'.
